export * from './newtask-form/newtask-form.component';
export * from './task-input/input-task.component';
export * from './task-input/input-task.component';
export * from './list-item/list-item.component';
export * from './task-item/task-item.component';
export * from './calendar/calendar.component';
export * from '../base/kpi/kpi.component';
export * from './modal';
export * from './edit-task-form';
